Enhancement/94 remove unused profile pics
bregenz-bewegt/bregenz-bewegt pull request #100
Opened 2022-10-24 07:59 UTC by TimonStadelmann

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | no                                         |
| New feature?         | no yes                                             |
| Related issues/PRs   | #94  |
| External ticket link |     |
| License              | MIT                                                |

#### What's in this PR?

#### Why?

2022-10-24 08:13 UTC, b3h3m0th requested changes

2022-10-24 08:13 UTC, b3h3m0th commented on prisma/seed.ts
> +        profilePicture: '6dad6d66-02b7-450b-9248-94a8c30563a6.jpeg',
dia hardcoded id kann ned funktioniera weil da uploads folder ned uf git gepushed wird.

2022-10-24 09:05 UTC, TimonStadelmann commented on prisma/seed.ts
> +        profilePicture: '6dad6d66-02b7-450b-9248-94a8c30563a6.jpeg',
ah ok. söll mas weg lo oder gäbs alternativen?

2022-10-24 09:13 UTC, b3h3m0th commented on prisma/seed.ts
> +        profilePicture: '6dad6d66-02b7-450b-9248-94a8c30563a6.jpeg',
i würds weglo. so züg kannsch du lokal uf dinam pc ihne speichern aba i find private daten ghören ned uf github.

2022-10-24 09:21 UTC, TimonStadelmann commented on prisma/seed.ts
> +        profilePicture: '6dad6d66-02b7-450b-9248-94a8c30563a6.jpeg',
ok👍

2022-10-27 06:56 UTC, TimonStadelmann commented
hey soll i do no was ändern, oder küntesch des bitte approven?

2022-10-27 10:39 UTC, b3h3m0th commented
I wart dass du a neue review request stellsch.
![image](https://user-images.githubusercontent.com/54234287/198263287-4a610b8b-8a43-4ad1-b051-8557de760179.png)
Es sin imma noch min altes review gültig.

2022-10-27 10:40 UTC, b3h3m0th approved these changes

2022-11-01 21:20 UTC, merged