Enhancement/21 map view
bregenz-bewegt/bregenz-bewegt pull request #132
Opened 2022-11-05 22:35 UTC by TimonStadelmann

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | no yes                                             |
| New feature?         | no yes                                             |
| Related issues/PRs   | #21 #101 #130 #131 |
| External ticket link |  |
| License              | MIT                                                |

#### What's in this PR?

#### Why?

2022-11-06 13:46 UTC, b3h3m0th requested changes

2022-11-06 13:46 UTC, b3h3m0th commented on libs/client/common/stores/src/lib/park.store.ts
> +  ): Promise<Park | undefined> {
:( Warum hosch des ussa to haha des mar a mega coole line ma sia direkt dasses a array zruck gibt mir genau einer exercise

2022-11-06 13:46 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/map/map.tsx
> +export const Map: React.FC<MapProps> = ({ parks }: MapProps) => {
Frage: Findesch es besser wenns die liste und die map in da components sin? Vllt künnt mas so wie mas bei bam profile gmacht hon maha. dass mas im pages folder atomisiert:

```
pages/
├─ src/
│  ├─ lib/
│  │  ├─ start/
│  │  │  ├─ map/
│  │  │  │  ├─ map.tsx
│  │  │  │  ├─ map.scss
│  │  │  ├─ list/
│  │  │  │  ├─ list.tsx
│  │  │  │  ├─ list.scss
│  │  │  ├─ start.tsx
│  │  │  ├─ start.scss
```

2022-11-06 13:46 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/transition-block/transition-block.scss
> +}
Hmm I woas ned ob dean gradient an der stelle so nice find. I finds iwi zu viel weil mir hon uf da karten o scho a biz an schatta domma:

![image](https://user-images.githubusercontent.com/54234287/200174081-c1ae883d-9040-48d8-b73c-8eec99b72f9d.png)

2022-11-06 13:46 UTC, b3h3m0th commented on prisma/seed.ts
> +    ],
Du hosch jo do jetzt quasi a matrix gmacht. wärs ned übersichtlicher wemmas so macht:

```
{
  id: 1,
  name: 'Parkourpark Remise',
  address: 'Badgässele',
  image: 'https://picsum.photos/400/200,
  qr: 'not-yet-defined-0',
  coordinates: {
    latitude: 47.498273,
    longitude: 9.703772,
  }
},
```

Denn müsstma dunna ned mit `park[0]` uns so schaffa

2022-11-06 13:46 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/map/map.scss
> +@import url(https://unpkg.com/leaflet@1.9.2/dist/leaflet.css);
Gibt's für des villicht a möglichkeit des direkt als file zum inkludieren denn wärma ned vo irgendwelchna cloud packages abhängig 🤔 vllt usam dist folder vo leaflet us da node_modules

2022-11-06 13:48 UTC, b3h3m0th commented
Villicht no a kleinigkeit: Nocham onboarding künntma direkt zur registration verlinken und ned zum login. macht mehr sinn findi. isch ma davor iwi noch nia ufgfalla

2022-11-06 15:05 UTC, b3h3m0th commented on libs/client/common/stores/src/lib/park.store.ts
> +import {} from 'rxjs';
glob des war a versehen oda

2022-11-06 15:06 UTC, b3h3m0th commented on libs/client/common/stores/src/lib/park.store.ts
> +import e from 'express';
des schaut ma noch falscher autocompletion von nam try catch us haha

2022-11-07 09:08 UTC, TimonStadelmann commented
@b3h3m0th  bitte GoToLocation button aschoa

2022-11-07 09:18 UTC, TimonStadelmann commented on libs/client/ui/components/src/lib/transition-block/transition-block.scss
> +}
wenn behalten, nur 1 nicht 3

2022-11-07 09:26 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/transition-block/transition-block.scss
> +}
Entscheidung:

```
height: 16px;
```

2022-11-07 11:53 UTC, b3h3m0th requested changes

2022-11-07 11:53 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/transition-block/transition-block.scss
> +  // Generated width cssgradient.io
des künnt ma noch ussalöscha

2022-11-07 12:03 UTC, TimonStadelmann commented on libs/client/ui/components/src/lib/transition-block/transition-block.scss
> +  // Generated width cssgradient.io
scho? i hobs nämlich extra inegschriba, für future devs

2022-11-07 12:18 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/transition-block/transition-block.scss
> +  // Generated width cssgradient.io
nana i würds ussa tua mir bruchan kua schleichwerbung haha

2022-11-07 13:39 UTC, b3h3m0th approved these changes

2022-11-07 13:39 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/transition-block/transition-block.scss
> +
do isch an abstand der kann o weg haha

2022-11-07 14:30 UTC, TimonStadelmann commented on libs/client/ui/components/src/lib/transition-block/transition-block.scss
> +
haha

2022-11-07 15:21 UTC, b3h3m0th approved these changes

2022-11-08 09:47 UTC, b3h3m0th approved these changes

2022-11-08 09:48 UTC, merged