Create Statistic page
bregenz-bewegt/bregenz-bewegt pull request #161
Opened 2022-11-14 19:46 UTC by TimonStadelmann

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | no yes                                             |
| New feature?         | no yes                                             |
| Related issues/PRs   |  closes #138  |
| External ticket link |      |
| License              | MIT                                                |

#### What's in this PR?

#### Why?

2022-11-19 13:23 UTC, TimonStadelmann commented
Es isch alles fertig, aber beim design vo da activity-cards bin i ma no unsicher.

2022-11-19 21:49 UTC, b3h3m0th requested changes
Nice!!

2022-11-19 21:49 UTC, b3h3m0th commented on libs/client/types/src/lib/entities/activity.ts
> +}[];
Für des würdi a eigene datei in z. B. `@bregenz-bewegt/client/types` maha. weil bei da entities söttan wirklich nur datenbank relevante entities si

2022-11-19 21:49 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/activity-card/activity-card.scss
> +  padding: var(--spacing-s) var(--spacing-m);
I find es schaut besser us wemma nur `padding: var(--spacing-m);` macht.

2022-11-19 21:49 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/activity-card/activity-card.tsx
> +          <div>{activity.park.name}</div>
villicht kama do wia bei da park card bei da start page noch a location icon ihne tua 🤔

2022-11-19 21:49 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/analytics/analytics.scss
> +          );
des isch richtig geil wia des denn sticky blibt haha 💯

2022-11-19 21:49 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/analytics/analytics.tsx
> +    const RELOAD_CHUNK_SIZE = 5;
sowas würdi außerhalb vom component definieren. denn wirds ned bei jeden render neu erstellt.

2022-11-19 21:49 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/analytics/analytics.tsx
> +    type calculateTicksProps = {
des würdi o außerhalb vom component definieren

2022-11-19 21:49 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/analytics/analytics.tsx
> +              </h2>
kama dia schrift villicht a kle dezenter maha. i find es isch zu mächtig und ma künnt "Münzen im {month}" noch durch "B-Bucks gesammelt im {month}" ersetzen.

2022-11-19 21:49 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/analytics/analytics.tsx
> +            <ArrowCircleUp size={32} color="white" variant="Bold" />
Do würdi da z. B. da `ArrowUp2` verwenda oder irgendwas ohne da weiße circle rund herum. so a normales chevron findi passender iwi.

2022-11-19 21:49 UTC, b3h3m0th commented on libs/server/controllers/activity/src/lib/activity.service.ts
> +  }
fancy shit haha 👍

2022-11-19 21:52 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/activity-card/activity-card.tsx
> +          <div>{activity.exercise.name}</div>
Kama do ned mit IonCardTitle und so schaffa?

2022-11-19 21:55 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/activity-card/activity-card.tsx
> +export const ActivityCard: React.FC<ActivityCardProps> = ({
Bezüglich design vo da card. I find ma sött grundsätzlich so viel wie möglich ionic components verwenda und so wenig wie möglich custom styled divs und so. weils denn isches zum einen einheitlich und zum andera uf allna plattformen getested, richtig gestyled und ma hot die probleme mit spacings, font-sizes, font-weights etc. ned. ma würd sich o viel scss sparen weil ma ned alles manuell setzen muss.

2022-11-25 09:05 UTC, b3h3m0th approved these changes

2022-11-25 09:09 UTC, b3h3m0th approved these changes

2022-11-25 09:18 UTC, merged