Disable analytics guest
bregenz-bewegt/bregenz-bewegt pull request #233
Opened 2022-12-15 11:26 UTC by TimonStadelmann

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | no yes                                             |
| New feature?         | no yes                                             |
| Related issues/PRs   | closes #211 closes #229 closes #213  |
| External ticket link |      |
| License              | MIT                                                |

#### What's in this PR?

#### Why?

2022-12-16 09:35 UTC, b3h3m0th requested changes
nice

2022-12-16 09:35 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/analytics/analytics.tsx
> +    const guestMockChart = [
kama die mockdata a biz ändra, dass da graph a biz spektakulärer usluagt und da ganze graph betrifft.

2022-12-16 09:35 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/analytics/analytics.tsx
> +          <GuestLock
des guest lock modal isch über die ganze breite. halt es fehlt der padding vom main page container wo wo außen noch an padding dazua kut. 
![image](https://user-images.githubusercontent.com/54234287/208068413-04221907-a3ea-4c63-a4e3-796c04d22d53.png)
![image](https://user-images.githubusercontent.com/54234287/208068480-26f30ab6-a16e-4af6-85dc-95d4d935ce60.png)

2022-12-16 09:35 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/analytics/analytics.tsx
> +                <div className="analytics__content__list">
kama do vllt wie beim leaderboard o noch mockdata ihne tua?

2023-02-02 13:27 UTC, b3h3m0th requested changes
Bitte des lock einheitlich macha. jetzt isches ufam profil andersch.
Wenn du bei da analytics die sitta reloadesch krigsch an 403.

2023-02-02 14:47 UTC, TimonStadelmann commented
was isch net einheitlich? Wirft es im Main koan 403 beim Reloaden

2023-02-03 06:57 UTC, b3h3m0th commented
Die Locks sin ned einheitlich. Dia uana hon an schatten die andra ned. des uane blurred und verdunkelt da hintergrund, andre ned. Und bezüglich 403: Da Sinn vo derra PR isch, dean Fehler zum beheben, also jo es isch o im main.

2023-02-03 08:48 UTC, TimonStadelmann commented
Da Fehler hob i doch im Competitor Detail behoba, wie gset?? Und des isch net der Sinn vo deam Pull Request. Des Issue isch sogar dem competitor detail zugewiesen

2023-02-03 10:02 UTC, b3h3m0th approved these changes
perfekt!

2023-02-03 10:50 UTC, merged