Impressum, ToS & Sponsors
bregenz-bewegt/bregenz-bewegt pull request #273
Opened 2023-01-04 16:07 UTC by b3h3m0th

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | no |
| New feature?         | yes                                             |
| Related issues/PRs   | closes #271, closes #272 |
| External ticket link |      |
| License              | MIT                                                |

#### What's in this PR?

#### Why?

2023-01-09 20:07 UTC, TimonStadelmann requested changes
ToS ussam Titel löscha oder no dazua macha bitte

2023-01-09 20:07 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +                      <h2>Sonstiges</h2>
bitte an anderer Name

2023-01-09 20:47 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +                      <h2>Sonstiges</h2>
Mir isch nix besseres igfalla. Hosxh an vorschlag?

2023-01-11 12:32 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +                      <h2>Sonstiges</h2>
Unter Account Created at

2023-01-16 09:55 UTC, TimonStadelmann approved these changes

2023-01-16 09:58 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +                      <h2>Sonstiges</h2>
I hob da name jetzt zu "Rechtliches" geändert

2023-01-17 08:27 UTC, merged