Competitor detail
bregenz-bewegt/bregenz-bewegt pull request #277
Opened 2023-01-09 12:28 UTC by TimonStadelmann

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | yes also                                             |
| New feature?         | yes                                             |
| Related issues/PRs   |  closes #265 closes #184 closes #175 closes #274 |
| External ticket link |      |
| License              | MIT                                                |

#### What's in this PR?

#### Why?

2023-02-16 13:48 UTC, b3h3m0th commented
bam ersten rendern vom leaderboard:
![image](https://user-images.githubusercontent.com/54234287/219382284-81d37758-df5e-465c-b46a-fdbce1581657.png)

2023-02-16 14:16 UTC, b3h3m0th requested changes

2023-02-16 14:16 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/competitor.controller.ts
> +    if (!comp) return undefined;
der check isch useless

2023-02-16 14:16 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/competitor.controller.ts
> +    const comp = await this.userService.findByUsername(username);
bitte die variable einfach `competitor` verwenda. die abkürzung hot kuan vorteil findi

2023-02-16 14:16 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/competitor.controller.ts
> +    const comp = await this.userService.findByUsername(username);
bitte einfach `competitor` benenna

2023-02-16 14:16 UTC, b3h3m0th commented on libs/client/ui/components/src/lib/back-button/back-button.tsx
>  export const BackButton: React.FC<BackButtonProps> = ({
Generell bezüglich deam BackButton:
Der backbutton brucht im `ion-header` immer an speziella spacing und des hosch du in jeder page dazua gmacht. Da des jetzt so oft vorkut also idee des ganze einfach in a globales `ion-header.scss` styling auslagern. Denn kannsch mine ganzen kommentare bezüglich verschachteln und so ignorieren.

2023-02-20 08:06 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/analytics/analytics.tsx
> +                        <React.Fragment key={i}>
Sunsch kann i koan key vergeaba, denn gäbs an console error/warning

2023-02-20 08:26 UTC, TimonStadelmann commented on libs/client/ui/components/src/lib/textarea/textarea.scss
> +      --background: var(--ion-color-light-tint) !important;
? des sind die custom css properties, aber des important brucht es nur bei padding-start hob i gmerkt👍

2023-02-20 08:29 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/analytics/analytics.tsx
> +                        <React.Fragment key={i}>
Ahh okay macht Sinn

2023-02-22 13:19 UTC, b3h3m0th approved these changes
also i find ma kanns mergen, nur die skeletons im leaderboard künnt ma spöter no apassa. avatar no rund und username breiter

2023-02-24 10:01 UTC, merged