Landing page
bregenz-bewegt/bregenz-bewegt pull request #304
Opened 2023-01-23 12:11 UTC by b3h3m0th

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | no                                              |
| New feature?         | yes                                             |
| Related issues/PRs   | closes #146 |
| External ticket link |      |
| License              | MIT                                                |

#### What's in this PR?

#### Why?

2023-02-01 08:09 UTC, TimonStadelmann requested changes
Größter change wird wahrscheinlich Ersetzung mit screenshots sie. I kann da die Screenshots vo da Powerpoint schicka

2023-02-01 08:09 UTC, TimonStadelmann commented on libs/landing-page/pages/src/lib/home/home.tsx
> +    <div className="home">
vorschlag: id verwenda

2023-02-01 08:09 UTC, TimonStadelmann commented on libs/landing-page/pages/src/lib/privacy-police/privacy-police.tsx
> +    <div className="privacy-police">
für was brucht es dean wrapper

2023-02-01 08:49 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/register/register.tsx
> +                    Ich akzeptiere Datenschutz und Nutzungsbedingungen
des hobi do gmacht https://github.com/bregenz-bewegt/bregenz-bewegt/pull/313

2023-02-01 08:53 UTC, b3h3m0th commented on apps/landing-page-e2e/src/e2e/app.cy.ts
> +  it('should display welcome message', () => {
end to end tests. i lösch dean example test mol ussa. aba des grundlegende generierte schema würdi gern bheba falls mas mol brucht.

2023-02-01 08:53 UTC, b3h3m0th commented on apps/landing-page-e2e/src/fixtures/example.json
> +}
würds gern bheba als example.

2023-02-01 08:53 UTC, b3h3m0th commented on apps/landing-page-e2e/src/support/commands.ts
> +// Cypress.Commands.overwrite("visit", (originalFn, url, options) => { ... })
isch o generiert

2023-02-01 08:53 UTC, b3h3m0th commented on apps/landing-page/src/theme/styles/html.scss
> +  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
Eigentlich ned. solli an anderer verwenda?

2023-02-01 08:55 UTC, b3h3m0th commented on apps/landing-page/src/theme/variables/spacings.scss
> +:root {
des hobi ma zersch überlegt. des problem isch, dass des blöd isch des scss zum resolven weilma denn custom bundler options schriba muss. außerdem wird gar ned so viel geteilt. die farben beispielsweise hoaßan jo bei ionic andasch

2023-02-01 08:55 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +                      <IonLabel>Datenschutzbestimmungen</IonLabel>
Ah ok fix

2023-02-01 08:56 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/footer/footer.tsx
> +        <a href="/privay-police">Datenschutz</a>
passt

2023-02-01 08:57 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/hero/hero.tsx
> +            <span className="hero__info__text-part__hidden">
es isch a eigenes verschachteltes element

2023-02-01 08:58 UTC, b3h3m0th commented on libs/landing-page/pages/src/lib/home/home.tsx
> +    <div className="home">
wia muansch?

2023-02-01 08:59 UTC, b3h3m0th commented on libs/landing-page/pages/src/lib/privacy-police/privacy-police.tsx
> +    <div className="privacy-police">
Denn hobi an schüana abgekapselter component für client und landing-page und grief ned kreuz und quer uf components zu

2023-02-01 09:00 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +                      <IonLabel>Datenschutzbestimmungen</IonLabel>
i mach des aba o in #312

2023-02-01 09:05 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/footer/footer.tsx
> +        &#169; {new Date().getFullYear()} Landeshauptstadt Bregenz
wundert mi gad, dass du des ned gfixt hosch des hobi mol iwo kommentiert. hobs jetzt über da context gefixt

2023-02-01 09:06 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/footer/footer.tsx
> +export interface FooterProps {}
true

2023-02-01 09:08 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/hero/hero.scss
> +        background-image: linear-gradient(90deg, #0065bd, #74afe2, #0065bd);
stimmt do tuat i noch di variable ihne

2023-02-01 09:09 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/mockup/mockup.tsx
> +          <iframe
yess

2023-02-01 09:47 UTC, b3h3m0th commented
Sorry hob zu früh a re-review requested. i muss zersch die screenshots ihne tuat

2023-02-01 14:15 UTC, b3h3m0th commented
So jetzt isches ready für review @TimonStadelmann

2023-02-02 09:50 UTC, TimonStadelmann commented on apps/landing-page/src/theme/styles/html.scss
> +  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
eigana branch

2023-02-03 09:50 UTC, TimonStadelmann commented on apps/landing-page-e2e/src/e2e/app.cy.ts
> +  it('should display welcome message', () => {
fehlt no

2023-02-03 09:54 UTC, TimonStadelmann commented on libs/landing-page/components/src/lib/footer/footer.tsx
> +export interface FooterProps {}
fehlt no

2023-02-03 09:55 UTC, TimonStadelmann commented on libs/landing-page/components/src/lib/hero/hero.scss
> +        background-image: linear-gradient(90deg, #0065bd, #74afe2, #0065bd);
fehlt no

2023-02-03 10:00 UTC, TimonStadelmann commented on libs/landing-page/pages/src/lib/home/home.scss
> +}
?

2023-02-03 10:03 UTC, b3h3m0th commented on apps/landing-page-e2e/src/e2e/app.cy.ts
> +  it('should display welcome message', () => {
nope isch gefixt

2023-02-03 10:03 UTC, b3h3m0th commented on libs/landing-page/pages/src/lib/home/home.scss
> +}
isch gefixt

2023-02-03 10:03 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/footer/footer.tsx
> +export interface FooterProps {}
na isch gefixt

2023-02-03 10:04 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/hero/hero.scss
> +        background-image: linear-gradient(90deg, #0065bd, #74afe2, #0065bd);
na isch gefixt

2023-02-03 10:19 UTC, TimonStadelmann requested changes
HBS und mail.service künnt ma no die line end ändern

2023-02-03 10:19 UTC, TimonStadelmann commented on libs/landing-page/components/src/lib/hero/hero.scss
> +    padding-right: 32px;
magic number

2023-02-03 10:19 UTC, TimonStadelmann commented on libs/landing-page/components/src/lib/hero/hero.scss
> +    padding-left: 32px;
no o variable

2023-02-03 10:19 UTC, TimonStadelmann commented on libs/landing-page/components/src/lib/hero/hero.scss
> +      height: 7rem;
evtl. o Variable

2023-02-03 10:19 UTC, TimonStadelmann commented on libs/landing-page/components/src/lib/mockup/mockup.scss
> +    left: -100px;
variable villicht

2023-02-03 10:19 UTC, TimonStadelmann commented on libs/landing-page/components/src/lib/mockup/mockup.scss
> +  border-radius: calc(var(--spacing-xl) + var(--spacing-m) - var(--spacing-xs));
got des villicht simpler

2023-02-03 10:19 UTC, TimonStadelmann commented on libs/landing-page/components/src/lib/mockup/mockup.tsx
> +      ) : null}
bruchts villicht nümma weils jo jetzt screens sind

2023-02-03 10:28 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/hero/hero.scss
> +      height: 7rem;
näh

2023-02-03 10:28 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/mockup/mockup.scss
> +    left: -100px;
näh

2023-02-03 10:56 UTC, TimonStadelmann requested changes
bitte discussions immer beantworta bevor gschlossa wird, sunsch woas i dine Begründung net

2023-02-03 12:09 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/hero/hero.scss
> +    padding-right: 32px;
true

2023-02-03 12:09 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/hero/hero.scss
> +    padding-left: 32px;
true

2023-02-03 12:09 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/mockup/mockup.scss
> +  border-radius: calc(var(--spacing-xl) + var(--spacing-m) - var(--spacing-xs));
joa na

2023-02-03 12:09 UTC, b3h3m0th commented on libs/landing-page/components/src/lib/mockup/mockup.tsx
> +      ) : null}
stimmt

2023-02-03 12:14 UTC, b3h3m0th commented
I marks imma als resolved wenni din kommentar genau so übernimm. denn woasi dass is erledigt hob bei da review fixes.

2023-02-03 12:40 UTC, TimonStadelmann approved these changes

2023-02-03 12:42 UTC, b3h3m0th commented
lets go!

2023-02-03 12:42 UTC, merged