completed
bregenz-bewegt/bregenz-bewegt pull request #53
Opened 2022-09-21 19:54 UTC by TimonStadelmann

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | no                                              |
| New feature?         |  yes                                             |
| Related issues/PRs   | #48  |
| External ticket link | https://trello.com/c/ChLZgc8d    |
| License              | MIT                                                |

#### What's in this PR?

#### Why?

2022-09-22 07:18 UTC, b3h3m0th commented
I vastand ned wie des funktionieren soll. Falls ma sine email wirklich ändern künna sollte, warum bestätigt ma denn die alte email? I denk dass die ganze email ändern sache wirklich irrelevant isch. da task war doch nur des email feld im frontend so wie davor da Benutzername.

Des styling vo da buttons isch do o widda andasch. war des absicht?
![image](https://user-images.githubusercontent.com/54234287/191683102-22ce9eab-eb8c-4abd-ac94-e1f1e9469cb5.png)

2022-09-22 07:30 UTC, b3h3m0th requested changes
Do müssma villicht mim jonas noml in da schual reda. i bin bisher davo usganga dass des nur a display feld wird unds des feature email ändenr gar ned gibt.

2022-11-05 23:45 UTC, TimonStadelmann commented
Isch jetzt net die schönste Lösung - es wird jetzt halt die alte email adresse überschriba bevor die neue übprüft wird.
Ma wird jetzt einfach noch am ändern usgloggt so dass ma, wie noch am registriera erst wieder den account verwenda kann wenn ma die Email bestätigt - was natürlich gefährlich sie kann wenn ma sich bei da email verschribt deswegen söts eigentlich o no an email ändern in da Verification geaba (hob i bei #124 no dazua gschriba)

2022-11-06 13:12 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +        const emailChanged = values.email !== userStore?.user?.email;
Warum muss ma da change do noml manuell überprüfen? Ma kann eh ned submitten wenn nix gechanged hot oda?

2022-11-06 13:12 UTC, b3h3m0th commented on libs/shared/types/src/lib/dto/user/patch-profile.dto.ts
> +  active?: boolean;
Für was bruchtma die `active` property?

2022-11-07 18:29 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +                  <h2>Kontoinformationen</h2>
mh viellicht eher Kontoeinstellungen oder no besser Sicherheit, Kontosicherheit, Sicherheitseinstellungen - weil jo email und passwort

2022-11-07 18:30 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +                  <h2>Kontoinformationen</h2>
Guata idee

2022-11-07 18:32 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +              </IonRow>
Denn künnama aber die ionrow und die drunter löscha wenn ma a eigene sitta drus machen, oder?

2022-11-07 18:48 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +              </IonRow>
😂 jo sry, hob denkt du bisch scho fertig weil es uf open war - aber des war jo i

2022-11-10 10:51 UTC, b3h3m0th approved these changes

2022-11-10 11:48 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/profile/email/email.tsx
> +            onVerifySuccess={handleVerifySuccess}
Künnt ma vereinfacha

2022-11-10 11:48 UTC, TimonStadelmann commented on libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
> +                    tab={page.route}
isn't needed?

2022-11-10 11:48 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.controller.ts
> +  Post as Post,
Bitte anschauen

2022-11-10 11:49 UTC, TimonStadelmann commented
ack

2022-11-10 11:55 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/email/email.tsx
> +            onVerifySuccess={handleVerifySuccess}
fixed

2022-11-10 11:56 UTC, merged