Preferences and Rank Checkbox
bregenz-bewegt/bregenz-bewegt pull request #57
Opened 2022-09-22 01:41 UTC by TimonStadelmann

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | no                                             |
| New feature?         | yes                                             |
| Related issues/PRs   | closes #56, closes #98 |
| External ticket link | https://trello.com/c/tRVpxV0K & https://trello.com/c/uAYHqAiT     |
| License              | MIT                                                |

#### What's in this PR?

#### Why?

2022-09-22 07:15 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +                <IonCheckbox slot="start"></IonCheckbox>
Warum hosch ned da custom component in `libs\client\ui\components\src\lib\checkbox\checkbox.tsx` verwendet? Denn hätts o mitm styles besser hinghaut.

2022-09-22 07:32 UTC, b3h3m0th requested changes
Funkt alles ganze nice. Aba s styling isch halt an brutala saustalla xD
![image](https://user-images.githubusercontent.com/54234287/191685636-8148a19a-16b9-428e-a390-014aa0fbf36c.png)

2022-10-24 13:27 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
I war am usprobiera wo da fehler war. I änders spöta widda zruck👍

2022-10-24 13:37 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
Danke danke. I hob da fehler aber gfunda. Bitte wenn du was "usprobiersch" net uffepushen. I werd do nochad viele merge conflicts fixa müssa

2022-10-24 13:39 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
da erste fehler bei mir war das da storekey falsch war

2022-10-24 13:47 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
i woas des hobi in deam commit scho gefixed: https://github.com/bregenz-bewegt/bregenz-bewegt/pull/57/commits/8771318e54910db95c0ec7c5c8bc8ebf6b0b0808

2022-10-24 13:47 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
> Danke danke. I hob da fehler glob gfunda. Bitte wenn du was "usprobiersch" net uffepushen. I werd do nochad viele merge conflicts fixa müssa

i hob die doch gfrogt ob du no was pushen musch? also kut doch no was?

2022-10-24 15:21 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
najo zu deam Zeitpunkt hob i nix mehr zum pushen khet, aber i werd jo no irgendwenn was pushen müssen. Nur halt no net jetzt

2022-10-24 15:22 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
also i würd jetzt behaupten i hobs sowitt gefixed, dasses funktioniert bis uf ua kleinigkeit dia i gad am ustüfteln bin

2022-10-24 16:01 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
ah ok - hob denkt du probirsch nur umma zum da fehler finda - was bisch no am ustüffteln?

2022-10-24 16:02 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
und was soll i jetzt mit den Änderungen vo mir Lokal macha - die kann i jo jetzt eigentlich löscha

2022-10-24 16:04 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.service.ts
> +          connectOrCreate: {
kann des o updaten?

2022-10-24 16:15 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.service.ts
> +      where: { id },
Wo wird denn jetzt aber festglegt was die user defaultmäßig für preferences hon?

2022-10-24 18:40 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/user.service.ts
> +      where: { id },
Bis jetzt gar kuane. alles uf null.

2022-10-25 12:40 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
was hosch du noch gmacht? i hätt jetzt alles gefixed. Soll is mol uffe pushen?

2022-10-25 12:42 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/user.service.ts
> +          connectOrCreate: {
i glob des isch num aktuell. i hob des durch a `upsert` (mischung us `update` und `insert`) ersetzt.

2022-10-25 13:04 UTC, b3h3m0th commented on libs/shared/types/src/lib/dto/user/patch-preferences.dto.ts
> +  public?: boolean;
also dass des ned funktioniert isch klar oda haha?

2022-10-25 15:51 UTC, b3h3m0th commented on libs/server/controllers/auth/src/lib/auth.service.ts
>          },
weil du mol gfrogt hosch wo die default preferences gsetzt werden. i hobs jetzt so gmacht, dass die preferences beim registrieren erstellt und connected werden. default sin:
- alle difficulties
- und a öffentliches profil
passt des?

2022-10-25 17:23 UTC, b3h3m0th commented on libs/server/controllers/user/src/lib/user.service.ts
> +      where: { id },
https://github.com/bregenz-bewegt/bregenz-bewegt/pull/57#discussion_r1004668387

2022-10-27 06:58 UTC, TimonStadelmann commented on libs/server/controllers/auth/src/lib/auth.service.ts
>          },
jo des passst für mi. Obwohl i des jetzt o so programmiert hob.

2022-10-27 07:01 UTC, TimonStadelmann commented on libs/shared/types/src/lib/dto/user/patch-preferences.dto.ts
> +  public?: boolean;
ups, gar net bemerkt hahah

2022-10-27 07:01 UTC, TimonStadelmann commented on libs/shared/types/src/lib/dto/user/patch-preferences.dto.ts
> +  public?: boolean;
danke

2022-10-27 07:02 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.service.ts
> +          connectOrCreate: {
ah ok 👍

2022-10-27 07:06 UTC, TimonStadelmann commented on libs/server/controllers/user/src/lib/user.service.ts
> +    const { preferences } = await this.prismaService.user.findUnique({
i hob o die fehler witta gsuacht und korrigiert, und des mit dam default preferences gmacht. Hob aber des im PatchPreferencesDto net gseana, deswegen wirds o net funktioniert ho.
du hosch eh scho Sacha uffe pushed. Push einfach alles uffe, sunsch müsst i jetzt die ganzen merge conflicts lösa und din "umma probiera" wieder löscha

2022-10-27 07:09 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +              {/* <IonRow className="profile__content__preferences">
des kommentar müsst ma no removen

2022-10-27 07:11 UTC, TimonStadelmann commented on libs/server/controllers/auth/src/lib/auth.service.ts
>          },
ah hob i doch net ganz so gmacht, warum isch des im Auth Service?

2022-10-27 07:16 UTC, TimonStadelmann commented
vo mir us passt sunsch alles👍

2022-10-27 11:04 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/profile.tsx
> +              {/* <IonRow className="profile__content__preferences">
ah danke

2022-10-27 11:06 UTC, b3h3m0th approved these changes

2022-10-27 11:08 UTC, merged