Activity Backend
bregenz-bewegt/bregenz-bewegt pull request #93
Opened 2022-10-17 15:53 UTC by b3h3m0th

| Q                    | A                                                  |
| -------------------- | -------------------------------------------------- |
| Bug fix?             | no |
| New feature?         | yes                                             |
| Related issues/PRs   | closes #92  |
| External ticket link |      |
| License              | MIT                                                |

2022-11-03 16:47 UTC, TimonStadelmann commented on libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
> +    return timespans;
Cool gmacht - guate idee mit dam `new Set(range)`
wenn an kürzerer oneliner wilsch küntesch sunsch o des returnen
`[...Array(diff + 1).keys()].map(x => range[0] - x)`
denn künnt ma die deklarierunga löscha vo diff und timespans und oa großes return schriba, falls des dir gfallt

2022-11-03 16:47 UTC, TimonStadelmann commented on libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
> +      ...(options?.skip !== undefined ? { take: options.take } : {}),
do woltesch wahrscheinlich `options?.take !==` schriba?

2022-11-03 16:47 UTC, TimonStadelmann commented on libs/shared/types/src/lib/dto/leaderboard/get-competitor.dto.ts
> +  @Transform(({ value }) => +value)
Macht des da value positiv, wenn er mol versehentlich negativ wär?

2022-11-03 16:47 UTC, TimonStadelmann commented on libs/server/controllers/activity/src/lib/activity.controller.ts
> +  @Post('start')
fehlt do net no `HasRole` und `UseGuards`?

2022-11-03 16:55 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/profile/difficulty/difficulty.tsx
> +        .catch(() => presentDefaultErrorToast());
haha danke. hob ma denkt des sött ma endlich mol uslagern weil des war wirklich 10 mol copy pasted dinna.

2022-11-03 17:13 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
> +          exerciseId: park?.exercises[0].id ?? -1,
Jo des stimmt scho weil eaba bei `parkStore?.getParkWithExercise(...)` an park mit anam array mit genau einem item (die konkrete übung wo ma gad isch) zruck kummt. Aba du hosch recht es isch eig echt schlecht getyped. Ma sieht gar ne was da unterschied isch zwischen `parkStore?.getParkWithExercise(...)` und `parkStore?.getParkWithExercises(...)` isch oda was generell abgoht es isch alles per default mit `any` inferred.

2022-11-03 17:28 UTC, b3h3m0th commented on libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
> +      ...(options?.skip !== undefined ? { take: options.take } : {}),
Ouhh sh*t. Danke!

2022-11-03 17:29 UTC, b3h3m0th commented on libs/shared/types/src/lib/dto/leaderboard/get-competitor.dto.ts
> +  @Transform(({ value }) => +value)
Na mit `+value` konvertierts da string zu einer number. des isch do iwi komisch dass ma des mit da `class-transformer` manuell maha muss aba irgendwie funktioniert bei queries da implizite conversion ned.

2022-11-03 17:30 UTC, b3h3m0th commented on libs/server/controllers/activity/src/lib/activity.controller.ts
> +  @Post('start')
Dürfen Gäste kua Übunga starten?

2022-11-03 17:38 UTC, TimonStadelmann commented on libs/server/controllers/activity/src/lib/activity.controller.ts
> +  @Post('start')
Ah jo, mol dürfen se. Sry

2022-11-03 17:39 UTC, TimonStadelmann commented on libs/shared/types/src/lib/dto/leaderboard/get-competitor.dto.ts
> +  @Transform(({ value }) => +value)
Ah ok, danke

2022-11-03 17:39 UTC, b3h3m0th commented on libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
> +    return timespans;
Ajo stimmt ma künnt echt einfach die keys nemma und da erste wert kanni o lo weils einfach `0` subtrahiert. nice nice.

2022-11-03 17:48 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
> +          exerciseId: park?.exercises[0].id ?? -1,
Ah ok. Danke.
I hob grad gseana das die ParkId (z. 80) im Backend glob garnet verwendet wird und o net in die Activity inegspeichert wird.
Wenn du se aber mitschicksch künten sie mir aber grad o in die Activity mitspeichern - so künnten mir denn o im Verlauf azoaga bei welchem Spielplatz die Übung gmacht worra isch - weil sunsch werden mir des o eigentlich garnet künna, weil Excercises bei mehreren Parks sie künnen

2022-11-03 17:50 UTC, TimonStadelmann commented on libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
> +    return timespans;
Genau, denn bruchts nämlich o net des Inline-IF

2022-11-03 17:52 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
> +          exerciseId: park?.exercises[0].id ?? -1,
Ajo stimmt. Ma woas bei ana activity eigentlich echt ned an welchen platz ma se gmacht hot. villicht künnt ma in da datenbank a zusätzliche relation alegga wo die activity mit dam park `1:1` verbunden isch.

2022-11-03 17:54 UTC, TimonStadelmann commented on libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
> +          exerciseId: park?.exercises[0].id ?? -1,
Genau, des wär nice👍

2022-11-03 17:58 UTC, b3h3m0th commented on libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
> +          exerciseId: park?.exercises[0].id ?? -1,
Nice denn machma des so. Hob no a issue erstellt (#114)

2022-11-03 19:12 UTC, TimonStadelmann requested changes

2022-11-03 19:12 UTC, TimonStadelmann commented on libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
>        diff > 1
des brucht es den o nümma

2022-11-03 19:14 UTC, b3h3m0th commented on libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
>        diff > 1
verdammt stimmt danke. sowit hobi ned denkt😂

2022-11-04 16:47 UTC, TimonStadelmann approved these changes

2022-11-04 16:47 UTC, TimonStadelmann commented on libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
> +      ...new Set([...Array(diff + 1).keys()].map((x) => range[0] - x)),
Für was des `new Set`?

2022-11-04 16:55 UTC, b3h3m0th commented on libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
> +      ...new Set([...Array(diff + 1).keys()].map((x) => range[0] - x)),
True des bruchts jo denna o numma.

2022-11-04 17:03 UTC, merged